name: Search ossbymaif on social networks

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - name: Search on twitter
        id: twitter
        run: node ./scripts/twitter.js
        with:
          twitter_bearer: ${{ secrets.TWITTER_BEARER }}
      # - name: Search on youtube
      #   id: youtube
      #   run: node ./scripts/youtube.js
      #   with:
      #     youtube_bearer: ${{ secrets.YOUTUBE_BEARER }}
      # - name: Search on medium
      #   id: medium
      #   run: node ./scripts/medium.js
      - name: Commit files
        run: |
          git config --local user.email "ossbymaif-github-actions@users.noreply.github.com"
          git config --local user.name "ossbymaif-github-actions"
          git add --all
          git commit -am "Update social network data"
      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}